####配置tomcat
server:
  port: 8080 #端口
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource: #mysql配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.12.123.158:3306/springboot_integration?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource #阿里druid连接池驱动配置信息
    druid:
      initial-size: 1   #初始连接数
      min-idle: 1   #最小连接数
      max-active: 10  #最大连接数
####jpa配置
  jpa:
    hibernate:
      #启动项目创建数据库新表
      ddl-auto: update
    #日志显示sql语句
    show-sql: true

####邮件配置
  mail:
    #邮箱服务器地址
    host: smtp.163.com
    #用户名
    username: quantianlong0420@163.com
    #密码
    password: tl12345678
    protocol: smtp


####mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**Mapper.xml
  type-aliases-package: com.tl.entity   #实体类扫描，多个package用","隔开
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker_str
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
#      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
####开启swagger文档
swagger:
  enable: true



fdfs:
  # 读取时间
  soTimeout: 1000
  # 连接超时时间
  connectTimeout: 2000
  # 编码默认UTF-8，charset属性不能自定义
  # charset: UTF-8
  # 缩略图
  thumbImage:
    # 宽
    width: 150
    # 高
    height: 150
  # tracker列表
  trackerList: 18.222.197.75:22122


####文件日志配置
#logging:
#  path: logs/